sodu: required
service:
    - docker
    
before_install:
    - docker build -t vortimid76/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true vortimid76/docker-react npm run test -- --coverage